# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 488c2688d5badbfb25bf4dc880e7ff4c34337e615cb39c8ad5e0cff2add720503c8723aab0bfd65cf6bc96d1b2166a2d7bacfacdff47250f132a317bdf1b8e42

test:
  secret_key_base: b4381c1add35ac67b99ab7050d32c35b63652f4c8ebb8424b5b29c808db42e091b27735d19e6615bc93cd93ccc77281ef95975f62a352d7ccf5254f9756d52c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
